#/bin/sh
qmk compile -kb keychron/q2/jis -km via -j 15
qmk compile -kb keychron/q2/ansi_encoder -km via -j 15
qmk compile -kb keychron/q2/ansi -km via -j 15
qmk compile -kb keychron/q2/jis_encoder -km via -j 15
qmk compile -kb keychron/q2/iso_encoder -km via -j 15
qmk compile -kb keychron/q2/iso -km via -j 15
qmk compile -kb keychron/q9/ansi_encoder -km via -j 15
qmk compile -kb keychron/q9/ansi -km via -j 15
qmk compile -kb keychron/q9/iso_encoder -km via -j 15
qmk compile -kb keychron/q9/iso -km via -j 15
qmk compile -kb keychron/q7/ansi -km via -j 15
qmk compile -kb keychron/q7/iso -km via -j 15
qmk compile -kb keychron/q60/ansi -km via -j 15
qmk compile -kb keychron/c2_pro/ansi/rgb -km via -j 15
qmk compile -kb keychron/v3/jis -km via -j 15
qmk compile -kb keychron/v3/ansi_encoder -km via -j 15
qmk compile -kb keychron/v3/ansi -km via -j 15
qmk compile -kb keychron/v3/jis_encoder -km via -j 15
qmk compile -kb keychron/v3/iso_encoder -km via -j 15
qmk compile -kb keychron/v3/iso -km via -j 15
qmk compile -kb keychron/v5/ansi_encoder -km via -j 15
qmk compile -kb keychron/v5/ansi -km via -j 15
qmk compile -kb keychron/v5/iso_encoder -km via -j 15
qmk compile -kb keychron/v5/iso -km via -j 15
qmk compile -kb keychron/q6/ansi_encoder -km via -j 15
qmk compile -kb keychron/q6/ansi -km via -j 15
qmk compile -kb keychron/q6/iso_encoder -km via -j 15
qmk compile -kb keychron/q6/iso -km via -j 15
qmk compile -kb keychron/q8/ansi_encoder -km via -j 15
qmk compile -kb keychron/q8/ansi -km via -j 15
qmk compile -kb keychron/q8/iso_encoder -km via -j 15
qmk compile -kb keychron/q8/iso -km via -j 15
qmk compile -kb keychron/q4/ansi -km via -j 15
qmk compile -kb keychron/q4/iso -km via -j 15
qmk compile -kb keychron/v10/ansi_encoder -km via -j 15
qmk compile -kb keychron/v10/iso_encoder -km via -j 15
qmk compile -kb keychron/c1_pro/ansi/rgb -km via -j 15
qmk compile -kb keychron/q11/ansi_encoder -km via -j 15
qmk compile -kb keychron/q11/iso_encoder -km via -j 15
qmk compile -kb keychron/q12/ansi_encoder -km via -j 15
qmk compile -kb keychron/q12/iso_encoder -km via -j 15
qmk compile -kb keychron/v8/ansi_encoder -km via -j 15
qmk compile -kb keychron/v8/ansi -km via -j 15
qmk compile -kb keychron/v8/iso_encoder -km via -j 15
qmk compile -kb keychron/v8/iso -km via -j 15
qmk compile -kb keychron/q9_plus/ansi_encoder -km via -j 15
qmk compile -kb keychron/q65/ansi_encoder -km via -j 15
qmk compile -kb keychron/v4/ansi -km via -j 15
qmk compile -kb keychron/v4/iso -km via -j 15
qmk compile -kb keychron/v6/ansi_encoder -km via -j 15
qmk compile -kb keychron/v6/ansi -km via -j 15
qmk compile -kb keychron/v6/iso_encoder -km via -j 15
qmk compile -kb keychron/v6/iso -km via -j 15
qmk compile -kb keychron/v1/jis -km via -j 15
qmk compile -kb keychron/v1/ansi_encoder -km via -j 15
qmk compile -kb keychron/v1/ansi -km via -j 15
qmk compile -kb keychron/v1/jis_encoder -km via -j 15
qmk compile -kb keychron/v1/iso_encoder -km via -j 15
qmk compile -kb keychron/v1/iso -km via -j 15
qmk compile -kb keychron/q5/ansi_encoder -km via -j 15
qmk compile -kb keychron/q5/ansi -km via -j 15
qmk compile -kb keychron/q5/iso_encoder -km via -j 15
qmk compile -kb keychron/q5/iso -km via -j 15
qmk compile -kb keychron/v2/jis -km via -j 15
qmk compile -kb keychron/v2/ansi_encoder -km via -j 15
qmk compile -kb keychron/v2/ansi -km via -j 15
qmk compile -kb keychron/v2/jis_encoder -km via -j 15
qmk compile -kb keychron/v2/iso_encoder -km via -j 15
qmk compile -kb keychron/v2/iso -km via -j 15
qmk compile -kb keychron/q3/jis -km via -j 15
qmk compile -kb keychron/q3/ansi_encoder -km via -j 15
qmk compile -kb keychron/q3/ansi -km via -j 15
qmk compile -kb keychron/q3/jis_encoder -km via -j 15
qmk compile -kb keychron/q3/iso_encoder -km via -j 15
qmk compile -kb keychron/q3/iso -km via -j 15
qmk compile -kb keychron/q1v2/jis -km via -j 15
qmk compile -kb keychron/q1v2/ansi_encoder -km via -j 15
qmk compile -kb keychron/q1v2/ansi -km via -j 15
qmk compile -kb keychron/q1v2/jis_encoder -km via -j 15
qmk compile -kb keychron/q1v2/iso_encoder -km via -j 15
qmk compile -kb keychron/q1v2/iso -km via -j 15
qmk compile -kb keychron/q1v1/ansi_encoder -km via -j 15
qmk compile -kb keychron/q1v1/ansi -km via -j 15
qmk compile -kb keychron/q1v1/iso_encoder -km via -j 15
qmk compile -kb keychron/q1v1/iso -km via -j 15
qmk compile -kb keychron/q10/ansi_encoder -km via -j 15
qmk compile -kb keychron/q10/iso_encoder -km via -j 15
qmk compile -kb keychron/v7/ansi -km via -j 15
qmk compile -kb keychron/v7/iso -km via -j 15
qmk compile -kb keychron/s1/ansi/rgb -km via -j 15
qmk compile -kb keychron/q0/plus -km via -j 15
qmk compile -kb keychron/q0/base -km via -j 15